name: simenv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - intel-openmp=2025.0.0
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - ncurses=6.5
  - numexpr=2.14.1
  - openssl=3.0.18
  - pandas=2.3.3
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14  # Keep Python 3.11 for compatibility. Use simenv_ros2 for ROS 2.
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - etils==1.13.0
      - evdev==1.9.2
      - fonttools==4.60.1
      - freetype-py==2.5.1
      - fsspec==2025.10.0
      - glfw==2.10.0
      - hello-robot-stretch-urdf==0.1.2
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - inputs==0.5
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - matplotlib==3.10.7
      - mujoco==3.2.6
      - mujoco-python-viewer==0.1.4
      - networkx==3.5
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==12.0.0
      - pycollada==0.9.2
      - pyglet==2.1.11
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pyribbit==0.1.46
      - python-xlib==0.33
      - pyyaml==6.0.3
      - scipy==1.16.3
      - trimesh==4.9.0
      - typing-extensions==4.15.0
      - urchin==0.0.30
      - zipp==3.23.0
      # ROS 2 dependencies (requires ROS 2 to be installed system-wide)
      # Install ROS 2 first: https://docs.ros.org/en/humble/Installation.html
      # Then install Python packages: pip install rclpy geometry-msgs sensor-msgs std-msgs
